### ISSUE TITLE
Learning Linux Commands

### ISSUE THREAD

**Issue by rabbitmac** [rabbitmac/LearningLinux#1]
This ticket is to track the time spend and the resource material document for linux commands.

**ToDo**

- [ ] Resource material or website link
- [ ] Basic linux commands
- [ ] Hands-on
- [ ] Document with snapshot
